---
sudo: required
services:
  - docker
branches:
  only:
    - master

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4d0c8fc4ca09ede7282e
      - https://api.opsgenie.com/v1/json/travisci?apiKey=dc0f16f7-e49d-4fa8-a920-9de1b9da1782
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

env:
  - DISTRO=alpine
  - DISTRO=ubuntu
  - DISTRO=ubuntu/14.04
  - DISTRO=ubuntu/15.04
  - DISTRO=ubuntu/15.10
  - DISTRO=debian
  - DISTRO=debian/jessie
  - DISTRO=debian/stable
  - DISTRO=centos
  - DISTRO=centos/5
  - DISTRO=centos/6
  - DISTRO=centos/7
  - DISTRO=opensuse
  - DISTRO=alpine
  - DISTRO=codenvy

script:
- docker build -t scottmiller171/"$DISTRO"-ansible:latest ./"$DISTRO"
- docker run -it scottmiller171/"$DISTRO"-ansible:latest ansible -i "localhost," -c local localhost -m ping
