---
sudo: required
services:
  - docker
branches:
  only:
    - master

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4d0c8fc4ca09ede7282e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

env:
  - DISTRO=ubuntu
  - DISTRO=debian
  - DISTRO=centos
  - DISTRO=opensuse
  - DISTRO=alpine

script:
- docker build -t scottmiller171/"$DISTRO"-ansible:latest ./"$DISTRO"
